# Generated by Django 2.1.2 on 2020-10-30 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(default='comments', max_length=20)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.Nursery_Manager')),
            ],
        ),
        migrations.AddField(
            model_name='plants',
            name='name',
            field=models.CharField(default='product', max_length=20),
        ),
        migrations.AddField(
            model_name='orders',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.Plants'),
        ),
        migrations.AddField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.Customer'),
        ),
    ]
